### ISSUE TITLE
Conflict in the footer with my section (Mourad merguoum)

### ISSUE THREAD

**Issue by mmerguoum** [mmerguoum/new-est#6]
@Laaziri-Abdo  @ismailerggab  @nourddin4 , SVP faites un review des deux section Footer avec ma section le conflit est dans l'image suivante : 

![conflict](https://user-images.githubusercontent.com/76811957/107982418-4e212400-6fc4-11eb-9dca-247e22daf247.png)

Vous avez toute la nuit,  

SVP pushez dans vos branche avec `git push origin your_branch`

Si vous voulez avoir les derniers changement faites un :  

`git fetch` puis `git pull origin branch`

L'issue et liée avec #5

**Comment by Laaziri-Abdo** [comment]
modification (tetle)
